import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Fogg Fresh Aromatic Black ",
    img: "https://m.media-amazon.com/images/I/51LYS95247L.jpg",
    rating: 4.2,
    price: "224",
    discount: 120,
    category: "Aromatic",
  },
  {
    _id: uuid(),
    title: "Fogg Fresh Deodorant Spicy Black",
    img: "https://m.media-amazon.com/images/I/717PPkZzQmL._SL1500_.jpg",
    rating: 4.1,
    price: "165",
    category: "Aromatic",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Axe Signature Body Perfume",
    img: "https://m.media-amazon.com/images/I/513g0xIuAKS._SL1500_.jpg",
    rating: 4.0,
    price: "266",
    category: "Aromatic",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Wild Stone Ultra Sensual ",
    img: "https://m.media-amazon.com/images/I/510kq0tXAzL._SL1000_.jpg",
    rating: 4.1,
    price: "359",
    category: "Aromatic",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Bella Vita Luxury FRESH",
    img: "https://m.media-amazon.com/images/I/61G42KyT+HL._SL1500_.jpg",
    rating: 4.0,
    price: "539",
    category: "Aromatic",
    discount: 100,
  },
  {
    _id: uuid(),
    title: "Bella Vita Luxury OUD PARFUM",
    img: "https://m.media-amazon.com/images/I/41ErX89NiyL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 3.8,
    price: "599",
    category: "Oriental, Woody",
    discount: 130,
  },
  {
    _id: uuid(),
    title: "Fogg Men's Woody and Aqua Black",
    img: "https://m.media-amazon.com/images/I/51XTtytLWpL._SX522_.jpg",
    rating: 4.8,
    price: "694",
    category: "Oriental, Woody",
    discount: 100,
  },
  {
    _id: uuid(),
    title: "Fogg Men's Woody ",
    img: "https://m.media-amazon.com/images/I/61fkovjAEpL._SX522_.jpg",
    rating: 4.8,
    price: "694",
    category: "Oriental, Woody",
  },
  {
    _id: uuid(),
    title: "John Phillips Wild Craft",
    img: "https://cdn.shopify.com/s/files/1/0572/5555/9307/products/Wild-Craft-_-Smog_1120x.jpg?v=1681893250",
    rating: 3.8,
    price: "1224",
    category: "Oriental, Woody",
    discount: 90,
  },
  {
    _id: uuid(),
    title: "Wild Stone Forest Spice ",
    img: "https://m.media-amazon.com/images/I/61rQb6MlfAL._SL1100_.jpg",
    rating: 4.2,
    price: "604",
    category: "Oriental, Woody",
  },
  {
    _id: uuid(),
    title: "JFogg Long-Lasting Fresh ",
    img: "https://m.media-amazon.com/images/I/41pg6du5ZLL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4.0,
    price: "341",
    category: "Oriental Fruity",
    discount: 100,
  },
  {
    _id: uuid(),
    title: "Fogg Men's Long-Lasting Fresh ",
    img: "https://m.media-amazon.com/images/I/71BMB3V0wqL._SL1500_.jpg",
    rating: 4.1,
    price: "357",
    category: "Oriental Fruity",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Wild Stone Night Rider ",
    img: "https://cdn.shopify.com/s/files/1/0651/3315/0443/products/NIGHT_RIDER_SPICE_PERFUME_30ML.jpg?v=1657972892",
    rating: 3.5,
    price: "197",
    category: "Oriental Fruity",
    discount: 150,
  },
  {
    _id: uuid(),
    title: "Engage Amber Hues  ",
    img: "https://m.media-amazon.com/images/I/61Jb5S5MlYL._SX522_.jpg",
    rating: 4.1,
    price: "421",
    category: "Oriental Fruity",
    discount: 110,
  },
  {
    _id: uuid(),
    title: "Bella Vita Luxury ",
    img: "https://m.media-amazon.com/images/I/6105WPa14IL._SX522_.jpg",
    rating: 4.8,
    price: "599",
    category: "Oriental Fruity",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Bella Vita Organic Flaura  ",
    img: "https://m.media-amazon.com/images/I/61Jb5S5MlYL._SX522_.jpg",
    rating: 3.9,
    price: "399",
    category: "Floral Fruity",
    discount: 80,
  },
  {
    _id: uuid(),
    title: "Fogg Women's Long-Lasting ",
    img: "https://m.media-amazon.com/images/I/71qS0pJMj9L._SX522_.jpg",
    rating: 4.2,
    price: "325",
    category: "Floral Fruity",
    discount: 50,
  },
  {
    _id: uuid(),
    title: "Engage W1 Perfume Spray",
    img: "https://m.media-amazon.com/images/I/71JZoLhUZ1L._SX522_.jpg",
    rating: 4.0,
    price: "225",
    category: "Floral Fruity",
    discount: 90,
  },
  {
    _id: uuid(),
    title: "Secret Temptation Dream  ",
    img: "https://m.media-amazon.com/images/I/51t7pw3ZcbL._SX522_.jpg",
    rating: 4.0,
    price: "259",
    category: "Floral Fruity",
    discount: 120,
  },
  {
    _id: uuid(),
    title: "Bella Vita Luxury Honey ",
    img: "https://m.media-amazon.com/images/I/61HAoKRKAUL._SX522_.jpg",
    rating: 4.2,
    price: "599",
    category: "Floral Fruity",
    discount: 110,
  },
];
